//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RightpointLabs.Pourcast.Web.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RightpointLabs.Pourcast.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Admin_Beer_Create_BackLink {
            get {
                return ResourceManager.GetString("Admin_Beer_Create_BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beer.
        /// </summary>
        public static string Admin_Beer_Create_Beer {
            get {
                return ResourceManager.GetString("Admin_Beer_Create_Beer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Admin_Beer_Create_SubmitButton {
            get {
                return ResourceManager.GetString("Admin_Beer_Create_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Beer.
        /// </summary>
        public static string Admin_Beer_Create_Title {
            get {
                return ResourceManager.GetString("Admin_Beer_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Admin_Brewery_Details_BackLink {
            get {
                return ResourceManager.GetString("Admin_Brewery_Details_BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Beer.
        /// </summary>
        public static string Admin_Brewery_Details_CreateLink {
            get {
                return ResourceManager.GetString("Admin_Brewery_Details_CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Admin_Brewery_Details_EditLink {
            get {
                return ResourceManager.GetString("Admin_Brewery_Details_EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Admin_Brewery_Details_Title {
            get {
                return ResourceManager.GetString("Admin_Brewery_Details_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Admin_Brewery_Edit_BackLink {
            get {
                return ResourceManager.GetString("Admin_Brewery_Edit_BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brewery.
        /// </summary>
        public static string Admin_Brewery_Edit_Brewery {
            get {
                return ResourceManager.GetString("Admin_Brewery_Edit_Brewery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Admin_Brewery_Edit_SaveButton {
            get {
                return ResourceManager.GetString("Admin_Brewery_Edit_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Admin_Brewery_Edit_Title {
            get {
                return ResourceManager.GetString("Admin_Brewery_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Admin_Brewery_Index_CreateLink {
            get {
                return ResourceManager.GetString("Admin_Brewery_Index_CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Admin_Brewery_Index_Title {
            get {
                return ResourceManager.GetString("Admin_Brewery_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Beer.
        /// </summary>
        public static string Admin_BreweryDetails_AddBeer {
            get {
                return ResourceManager.GetString("Admin_BreweryDetails_AddBeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Admin_BreweryDetails_BackToList {
            get {
                return ResourceManager.GetString("Admin_BreweryDetails_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beers.
        /// </summary>
        public static string Admin_BreweryDetails_Beers {
            get {
                return ResourceManager.GetString("Admin_BreweryDetails_Beers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Details.
        /// </summary>
        public static string Admin_BreweryDetails_FullDetails {
            get {
                return ResourceManager.GetString("Admin_BreweryDetails_FullDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Admin_BreweryList_Details {
            get {
                return ResourceManager.GetString("Admin_BreweryList_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Admin_CreateBrewery_Back {
            get {
                return ResourceManager.GetString("Admin_CreateBrewery_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brewery.
        /// </summary>
        public static string Admin_CreateBrewery_Brewery {
            get {
                return ResourceManager.GetString("Admin_CreateBrewery_Brewery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Admin_CreateBrewery_SubmitButton {
            get {
                return ResourceManager.GetString("Admin_CreateBrewery_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brewery.
        /// </summary>
        public static string Admin_CreateBrewery_Title {
            get {
                return ResourceManager.GetString("Admin_CreateBrewery_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Kegs.
        /// </summary>
        public static string Admin_Home_CurrentKegs {
            get {
                return ResourceManager.GetString("Admin_Home_CurrentKegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Keg On Tap.
        /// </summary>
        public static string Admin_Home_NoKeg {
            get {
                return ResourceManager.GetString("Admin_Home_NoKeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Admin_Home_Title {
            get {
                return ResourceManager.GetString("Admin_Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pourcast.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rightpoint.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montioring kegs so the beer never ends.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with Love in Chicago.
        /// </summary>
        public static string Made {
            get {
                return ResourceManager.GetString("Made", resourceCulture);
            }
        }
    }
}
